core/urls.py
"""
URLs for the core app.
"""

from django.urls import path
from .views import home_redirect, dashboard, view_contact_details

urlpatterns = [
    path('', home_redirect, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('bids/<int:bid_id>/view-contact/',
         view_contact_details, name='view_contact_details'),

]

currency_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import custom_logout
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/logout/', custom_logout, name='account_logout'),  
    path('accounts/', include('allauth.urls')),  
    path('', include('core.urls')), 
    path('offers/', include('offers.urls', namespace='offers')),     
    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password/reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    
]

offers/urls.py
"""
URL configuration for the Offers app.
Maps view functions to URL patterns.
"""
from django.urls import path
from . import views

app_name = 'offers'

urlpatterns = [
    path('', views.view_offers, name='view_offers'),
    path('create/', views.create_offer, name='create_offer'),
    path('edit/<int:pk>/', views.edit_offer, name='edit_offer'),
    path('delete/<int:pk>/', views.delete_offer, name='delete_offer'),
    path('<int:offer_id>/place_bid/', views.place_bid, name='place_bid'),
    path('bids/<int:bid_id>/accept/', views.accept_bid, name='accept_bid'),
    path('bids/<int:bid_id>/reject/', views.reject_bid, name='reject_bid'),
    path('<int:bid_id>/edit_bid/', views.edit_bid, name='edit_bid'),
    path('<int:bid_id>/delete_bid/', views.delete_bid, name='delete_bid'),
    path('<int:offer_id>/view_bids/', views.view_bids, name='view_bids'),
    path('bids/<int:bid_id>/share_contact/', views.share_contact,
         name='share_contact'),
    ]

offers/models.py
"""
Models for the Offers app.
Defines Offer, Bid, and LatestExchangeRate models.
"""
from django.db import models
from django.contrib.auth.models import User


class Offer(models.Model):
    """
    Represents an offer to buy or sell currency.
    """
    CURRENCY_CHOICES = [
        ('USD', 'US Dollar'),
        ('EUR', 'Euro'),
    ]

    RATE_TYPE_CHOICES = [
        ('FIXED', 'Fixed'),
        ('FLEXIBLE', 'Flexible'),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="offers")
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    exchange_rate = models.DecimalField(
        max_digits=8, decimal_places=3, null=True, blank=True)
    is_buying = models.BooleanField()
    rate_type = models.CharField(
        max_length=10, choices=RATE_TYPE_CHOICES, default='FIXED')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns a string representation of the offer.
        """

        return f"{'Buying' if self.is_buying else 'Selling'} {self.amount} \
        {self.currency} at {self.exchange_rate} ({self.rate_type})"

    class Meta:
        """
        Meta class for the Offer model.
        """
        ordering = ['-created_at']

    @property
    def conversion_amount(self):
        """
        Converts the offer amount to the target currency using the exchange
        rate.
        """
        if self.currency == "USD":
            return round(self.amount * self.exchange_rate, 2)
        elif self.currency == "EUR":
            return round(self.amount / self.exchange_rate, 2)
        return None


class LatestExchangeRate(models.Model):
    """
    Represents the latest exchange rate between two currencies.
    """
    base_currency = models.CharField(max_length=3, default="USD")
    target_currency = models.CharField(max_length=3, default="EUR")
    rate = models.DecimalField(max_digits=10, decimal_places=6)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        Returns a string representation of the exchange rate.
        """
        return f"{self.base_currency} to {self.target_currency}: {self.rate} \
        (updated {self.timestamp})"


class Bid(models.Model):
    """
    Represents a bid on an offer.
    """
    STATUS_CHOICES = [
        ('AWAITING', 'Awaiting Response'),
        ('ACCEPTED', 'Accepted'),
        ('REJECTED', 'Rejected'),
    ]

    offer = models.ForeignKey(
        'Offer', on_delete=models.CASCADE, related_name='bids')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='bids')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, choices=Offer.CURRENCY_CHOICES)
    exchange_rate = models.DecimalField(max_digits=8, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='AWAITING')
    contact_shared = models.BooleanField(default=False)

    class Meta:
        """
        Meta class for the Bid model.
        """
        unique_together = ('user', 'offer')

    def __str__(self):
        """
        Returns a string representation of the bid.
        """
        return f"Bid by {self.user.username} on {self.offer} \
        - Amount: {self.amount} ({self.get_status_display()})"

offers/views.py
"""
Views for the Offers app.
Defines the logic for handling offer and bid-related operations.
"""

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from .models import Offer, LatestExchangeRate, Bid
from .forms import OfferForm
from .utils import fetch_and_update_exchange_rate


@login_required
def create_offer(request):
    """
    Handles the creation of new offers.
    """
    next_url = request.GET.get('next', 'offers:view_offers')
    if request.method == "POST":
        form = OfferForm(request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.user = request.user
            if offer.rate_type == "FLEXIBLE" or not offer.exchange_rate:
                try:
                    latest_rate = LatestExchangeRate.objects.latest(
                                  "timestamp").rate
                except LatestExchangeRate.DoesNotExist:
                    latest_rate = fetch_and_update_exchange_rate()

                offer.exchange_rate = latest_rate

            offer.save()
            messages.success(request, "Offer created successfully.")
            return redirect(next_url)
    else:
        form = OfferForm()
    return render(request, 'offers/create_offer.html', {'form': form})


@login_required
def view_offers(request):
    """
    Displays a list of all available offers with optional filters.
    """
    offers = Offer.objects.prefetch_related('bids').all()
    is_buying = request.GET.get('is_buying')
    currency = request.GET.get('currency')
    rate_type = request.GET.get('rate_type')

    if is_buying in ['0', '1']:
        offers = offers.filter(is_buying=bool(int(is_buying)))

    if currency:
        offers = offers.filter(currency=currency)

    if rate_type:
        offers = offers.filter(rate_type=rate_type)

    for offer in offers:
        offer.user_bid = offer.bids.filter(user=request.user).first()
        offer.converted_amount = (
            round(offer.amount / offer.exchange_rate
                  if offer.currency == "EUR"
                  else offer.amount * offer.exchange_rate, 2)
        )
        offer.converted_amount_currency = ("EUR"
                                           if offer.currency == "USD"
                                           else "USD")
        offer.action = "Buying" if offer.is_buying else "Selling"
        if offer.user_bid:
            offer.bid_converted_amount = round(
                offer.user_bid.amount / offer.user_bid.exchange_rate
                if offer.user_bid.currency == "EUR"
                else offer.user_bid.amount * offer.user_bid.exchange_rate, 2
            )
            offer.bid_converted_currency = (
                "EUR" if offer.user_bid.currency == "USD" else "USD"
            )
        else:
            offer.bid_converted_amount = None
            offer.bid_converted_currency = None

    return render(request, 'offers/view_offers.html', {'offers': offers})


@login_required
def edit_offer(request, pk):
    """
    Handles the editing of existing offers.
    """
    offer = get_object_or_404(Offer, pk=pk)
    next_url = request.GET.get('next', 'offers:view_offers')
    if offer.user != request.user:
        return HttpResponseForbidden()

    if offer.bids.filter(status='ACCEPTED').exists():
        messages.error(
            request, "You cannot edit this offer as it has at least one \
            accepted bid.")
        return redirect(next_url)
    if request.method == "POST":
        form = OfferForm(request.POST, instance=offer)
        if form.is_valid():
            updated_offer = form.save(commit=False)
            if updated_offer.rate_type == "FLEXIBLE":
                try:
                    latest_rate = LatestExchangeRate.objects.latest(
                        "timestamp").rate
                except LatestExchangeRate.DoesNotExist:
                    latest_rate = fetch_and_update_exchange_rate()

                updated_offer.exchange_rate = latest_rate

            updated_offer.save()
            messages.success(request, "Offer updated successfully.")
            return redirect(next_url)
    else:
        form = OfferForm(instance=offer)
    return render(request, 'offers/edit_offer.html', {'form': form})


@login_required
def delete_offer(request, pk):
    """
    Handles the deletion of existing offers.
    """
    offer = get_object_or_404(Offer, pk=pk)
    if offer.user != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        offer.delete()
        messages.success(request, "Offer deleted successfully.")
        next_url = request.GET.get('next', 'offers:view_offers')
        return redirect(next_url)

    return render(request, 'offers/delete_offer.html', {'offer': offer})


@login_required
def place_bid(request, offer_id):
    """
    Handles the placement of bids on offers.
    """
    offer = get_object_or_404(Offer, id=offer_id)
    existing_bid = Bid.objects.filter(offer=offer, user=request.user).first()
    next_url = request.GET.get('next', 'offers:view_offers')

    if existing_bid:
        messages.error(
            request, "You have already placed a bid for this offer.")
        return redirect(next_url)

    if request.method == "POST":
        bid = Bid(
            offer=offer,
            user=request.user,
            amount=offer.amount,
            currency=offer.currency,
            exchange_rate=offer.exchange_rate,
        )
        bid.save()
        messages.success(request, "Bid placed successfully.")
        return redirect(next_url)

    return render(request, 'offers/place_bid.html', {'offer': offer})


@login_required
def view_bids(request, offer_id):
    """
    Displays a list of all bids on a particular offer.
    """
    offer = get_object_or_404(Offer, id=offer_id, user=request.user)
    offer.action = "Buying" if offer.is_buying else "Selling"
    offer.converted_amount = (
        round(offer.amount / offer.exchange_rate
              if offer.currency == "EUR"
              else offer.amount * offer.exchange_rate, 2))
    offer.converted_amount_currency = ("EUR"
                                       if offer.currency == "USD" else "USD")

    bids = offer.bids.all()
    has_accepted_bids = offer.bids.filter(status='ACCEPTED').exists()
    has_awaiting_bids = offer.bids.filter(status='AWAITING').exists()
    bids_exist = offer.bids.exists()
    for bid in bids:
        bid.converted_amount = (
            round(bid.amount / bid.exchange_rate
                  if bid.offer.currency == "EUR"
                  else bid.amount * bid.exchange_rate, 2)
        )
        bid.converted_amount_currency = ("EUR"
                                         if offer.currency == "USD" else "USD")
        bid.action = "Selling" if bid.offer.is_buying else "Buying"

    return render(request,
                  'offers/view_bids.html',
                  {'offer': offer,
                   'bids': bids,
                   'has_accepted_bids': has_accepted_bids,
                   'has_awaiting_bids': has_awaiting_bids,
                   'bids_exist': bids_exist
                   })


@login_required
def edit_bid(request, bid_id):
    """
    Handles the editing of existing bids.
    """
    bid = get_object_or_404(Bid, id=bid_id, user=request.user)
    offer = bid.offer
    next_url = request.GET.get('next', 'offers:view_offers')

    if bid.status != "AWAITING":
        messages.error(request,
                       "You cannot edit this bid as \
                       it has already been processed."
                       )
        return redirect(next_url)

    if offer.rate_type != "FLEXIBLE":
        messages.error(request,
                       "Bids can only be updated for offers with a flexible \
                       exchange rate.")
        return redirect(next_url)

    if request.method == "POST":
        try:
            latest_rate = LatestExchangeRate.objects.latest("timestamp").rate
        except LatestExchangeRate.DoesNotExist:
            latest_rate = offer.exchange_rate

        bid.exchange_rate = latest_rate
        bid.save()
        messages.success(request,
                         "Your bid has been updated with the latest exchange \
                         rate.")
        return redirect(next_url)

    return render(request, 'offers/edit_bid.html',
                  {'bid': bid, 'next': next_url, 'offer': offer})


@login_required
def accept_bid(request, bid_id):
    """
    Handles the acceptance of bids by offer owners.
    """
    bid = get_object_or_404(Bid, id=bid_id)
    if bid.offer.user != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        bid.status = "ACCEPTED"
        bid.save()
        messages.success(request, "You have accepted the bid.")
        next_url = request.GET.get('next', 'offers:view_offers')
        return redirect(next_url)


@login_required
def reject_bid(request, bid_id):
    """
    Handles the rejection of bids by offer owners.
    """
    bid = get_object_or_404(Bid, id=bid_id)
    if request.user != bid.offer.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        bid.status = "REJECTED"
        bid.save()
        messages.success(request, "You have rejected the bid.")
        next_url = request.GET.get('next', 'offers:view_offers')
        return redirect(next_url)


@login_required
def delete_bid(request, bid_id):
    """
    Handles the deletion of bids by users.
    """
    bid = get_object_or_404(Bid, id=bid_id, user=request.user)
    next_url = request.GET.get('next', 'offers:view_offers')

    if request.method == "POST":
        bid.delete()
        messages.success(request, "Your bid has been removed.")
        return redirect(next_url)

    return redirect(next_url)


@login_required

offers/templates/offers/create_offer.html
{% extends "base.html" %}
{% block title %}Create Offer{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="card p-4 shadow-lg">
        <h2 class="mb-4">Create Offer</h2>
        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-flex justify-content-end gap-2">
                <button type="submit" class="btn btn-primary">Create Offer</button>
                <a href="{% url 'offers:view_offers' %}" class="btn btn-secondary" aria-label="Cancel request">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

offers/templates/offers/edit_bid.html
{% extends "base.html" %}
{% block title %}Edit Bid{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="card p-4 shadow-lg">
        <h2 class="mb-4">Edit Your Bid</h2>
        <form method="post">
            {% csrf_token %}
            <p class="mb-3">
                Are you sure you want to update your bid for <strong>{{ bid.amount }} {{ bid.currency }}</strong>?
                The bid will be updated with the latest exchange rate.
            </p>
            <div class="d-flex justify-content-end gap-2">
                <button type="submit" class="btn btn-primary">Confirm</button>
                <a href="{% url 'offers:view_offers' %}" class="btn btn-secondary" aria-label="Cancel bid edition">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

offers/templates/offers/edit_offer.html
{% extends "base.html" %}
{% block title %}Edit Offer{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="card p-4 shadow-lg">
        <h2 class="mb-4">Edit Offer</h2>
        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-flex justify-content-end gap-2">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="{% url 'offers:view_offers' %}" class="btn btn-secondary" aria-label="Cancel offer edition">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

offers/templates/offers/view_bids.html
{% extends "base.html" %}
{% block title %}Bids for Offer{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="card p-4 shadow-lg">
        <h2 class="mb-4">Bids for Offer ID {{ offer.id }}</h2>        
        <p><strong>Created By:</strong> {{ offer.user.username }}</p>
        <p><strong>Offer: </strong>{{offer.amount}} {{offer.currency}}</p>
        <p><strong>Action:</strong> {{offer.action}}</p>
        <p><strong>Current Exchange Rate:</strong> {{ offer.exchange_rate }} €/$</p>
        <p><strong>Current Exchange Amount: </strong>{{offer.converted_amount}} {{offer.converted_amount_currency}}</p>
        <p><strong>Rate Type: </strong>{{offer.get_rate_type_display}}</p>

        <div class="table-responsive mt-4">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Bidder</th>
                        <th>Bid Amount</th>
                        <th>Bid Action</th>
                        <th>Exchange Rate</th>
                        <th>Exchange Amount</th>
                        {% if bids_exist %}
                        <th>Status</th>
                        {% endif %}
                        {% if has_awaiting_bids %}
                        <th>Actions</th>
                        {% endif %}
                        {% if has_accepted_bids %}
                        <th>Contact</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for bid in bids %}
                    <tr>
                        <td>{{ bid.user.username }}</td>
                        <td>{{ bid.amount }} {{ bid.offer.currency }}</td>
                        <td>{{ bid.action }}</td>
                        <td>{{bid.exchange_rate}}  €/$</td>
                        <td>{{ bid.converted_amount }} {{bid.converted_amount_currency}} </td>
                        <td>
                            <span class="badge {% if bid.status == 'AWAITING' %}bg-warning{% elif bid.status == 'ACCEPTED' %}bg-success{% else %}bg-secondary{% endif %}">
                                {{ bid.get_status_display }}
                            </span>
                        </td>
                        {% if has_awaiting_bids %}
                        <td>
                            {% if bid.status == "AWAITING" %}
                            <div class="d-flex flex-wrap gap-2">
                                <form method="post" action="{% url 'offers:accept_bid' bid.id %}?next={{request.path}}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success btn-sm">Accept</button>
                                </form>
                                <form method="post" action="{% url 'offers:reject_bid' bid.id %}?next={{request.path}}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm">Reject</button>
                                </form>
                            </div>
                            {% endif %}
                        </td>
                        {% endif %}
                        {% if has_accepted_bids %}
                        <td>
                            {% if bid.status == 'ACCEPTED' and not bid.contact_shared %}
                                <form method="post" action="{% url 'offers:share_contact' bid.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-info btn-sm">Share Contact</button>
                                </form>
                            {% elif bid.contact_shared %}
                                <span class="text-success">Contact Shared</span>
                            {% endif %}
                        </td>
                        {% endif %}
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">No bids found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

offers/templates/offers/view_offers.html
{% extends "base.html" %}
{%load static%}
{% block title %}View Offers{% endblock %}
{% block content %}
<div class="container mt-5">
    <!-- Header with Create Offer Button -->
    <!-- Create Offer Button -->
    {% if user.is_authenticated %}
    <div 
        class="d-flex justify-content-end mb-3">
        <a 
         href="{% url 'offers:create_offer' %}?next={{ request.path }}" 
         class="btn btn-primary w-100 w-md-auto" aria-label="Create a new offer">
         Create Offer
        </a>
    </div>
    {% endif %}

    <!-- Header with Filters -->
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-center mb-3">
        <h2 class="text-center text-md-start mb-2 mb-md-0">Active Offers</h2>

        <!-- Filter Section -->
        <form method="get" action="{% url 'offers:view_offers' %}" class="d-flex align-items-center gap-2">
            <label for="is_buying" class="visually-hidden">Transaaction Type:</label>
            <select name="is_buying" id="is_buying" class="form-select form-select-sm me-2">
                <option value="">All Actions</option>
                <option value="1" {% if request.GET.is_buying|default:'' == '1' %}selected{% endif %}>Buying</option>
                <option value="0" {% if request.GET.is_buying|default:'' == '0' %}selected{% endif %}>Selling</option>
            </select>
           <label for="currency" class="visually-hidden">Currency:</label>
            <select name="currency" id="currency" class="form-select form-select-sm me-2">
                <option value="">All Currencies</option>
                <option value="USD" {% if request.GET.currency == 'USD' %}selected{% endif %}>USD</option>
                <option value="EUR" {% if request.GET.currency == 'EUR' %}selected{% endif %}>EUR</option>
            </select>
            <label for="rate_type" class="visually-hidden">Rate Type:</label>
            <select name="rate_type" id="rate_type" class="form-select form-select-sm me-2">
                <option value="">All Rates</option>
                <option value="FIXED" {% if request.GET.rate_type == 'FIXED' %}selected{% endif %}>Fixed</option>
                <option value="FLEXIBLE" {% if request.GET.rate_type == 'FLEXIBLE' %}selected{% endif %}>Flexible</option>
            </select>
            <button type="submit" class="btn btn-primary btn-sm w-100 w-md-auto" aria-label="Filter Offers">Filter</button>
            <a href="{% url 'offers:view_offers' %}" class="btn btn-secondary btn-sm w-100 w-md-auto" aria-label="Reset filter values">Reset</a>
        </form>
    </div>

    <div class="row g-3">
        {% for offer in offers %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card shadow-sm offer-card ">
                <div class="card-body">
                    <h5 class="card-title">Offer ID: {{ offer.id}}</h5>
                    <p></p>
                    <p>Created By: <strong>{{offer.user.username}}</strong></p>
                    <p>Offer: <strong>{{offer.amount}} {{offer.currency}}</strong></p>
                    <p>Action: <strong>{{offer.action}}</strong></p>
                    <p>Exchange Rate: <strong>{{offer.exchange_rate}} €/$ </strong></p>                    
                    <p>Exchange Amount: <strong>{{offer.converted_amount}} {{offer.converted_amount_currency}}</strong></p>
                    <p>Exchange Type: <strong>{{offer.get_rate_type_display}}</strong></p>
                    <p>Created On: <strong>{{offer.created_at|date:"M d, Y"}}</strong></p>

                    <!-- Bid Status for Logged-in User -->
                    {% if offer.user_bid %}
                    <p class="card-text">
                        
                        <strong>------</strong> <br>
                        <strong>Your Bid:</strong> {{ offer.user_bid.amount }} {{offer.user_bid.currency}}<br>
                        <strong>In Exchange Of:</strong> {{ offer.bid_converted_amount }} {{ offer.bid_converted_currency }} <br>
                        <strong>Status:</strong> {{ offer.user_bid.get_status_display }}
                    </p>
                    {% endif %}

                    <!-- For Offer Creator -->
                    {% if user.is_authenticated and user == offer.user %}
                    <div>
                        <h6>Bids:</h6>
                        <p><strong>{{ offer.bids.count }}</strong> Bids Received</p>
                        <div class="action-buttons">
                            <a
                             href="{% url 'offers:view_bids' offer.id %}?next={{ request.path }}"
                             class="btn btn-primary btn-sm"
                             aria-label="View list of bids for offer">
                             View Bids
                            </a>
                            <a href="{% url 'offers:edit_offer' offer.id %}?next={{ request.path }}"
                               class="btn btn-warning btn-sm"
                               aria-label="Edit offer">                               
                               Edit Offer
                            </a>
                            <button
                                type="button"
                                class="btn btn-danger btn-sm"
                                data-bs-toggle="modal"
                                data-bs-target="#deleteConfirmationModal"
                                data-action="{% url 'offers:delete_offer' offer.id %}?next={{ request.path }}"
                                data-item="offer"
                                aria-label="Delete offer">
                                Delete Offer
                            </button>
                        </div>
                    </div>
                    {% else %}

                    <!-- For Bidders -->

                    <div class="bid-buttons">
                        {% if not offer.user_bid %}
                        <!-- Place Bid Button -->
                        <a href="{% url 'offers:place_bid' offer.id %}?next={{ request.path }}" 
                           class="btn btn-primary btn-sm"
                           aria-label="Place a bid for the offer">
                           Place Bid
                         </a>
                        {% else %}
                        <!-- Show Edit Bid Button Only if Status is AWAITING -->
                        {% if offer.user_bid.status == "AWAITING" %}
                        <a href="{% url 'offers:edit_bid' offer.user_bid.id %}?next={{ request.path }}" 
                           class="btn btn-warning btn-sm"
                           aria-label="Update your bid">
                           Update Your Bid
                        </a>
                        {% endif %}
                        {% endif %}
                        {% if offer.user_bid and offer.user_bid.id %}
                        <button
                            type="button"
                            class="btn btn-danger btn-sm"
                            data-bs-toggle="modal"
                            data-bs-target="#deleteConfirmationModal"
                            data-action="{% url 'offers:delete_bid' offer.user_bid.id %}?next={{ request.path }}"
                            data-item="bid"
                            aria-label="Delete your bid">
                            Delete Bid
                        </button>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Delete Confirmation Modal -->
{% include 'partials/delete_confirmation_modal.html' %}
{% block scripts %}
<script src="{% static 'js/delete_confirmation.js' %}"></script>
{% endblock %}
{% endblock %}